version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3.9.2-management
    container_name: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq:/etc/rabbitmq:rw
    ports:
      - "5672:5672"
      - "15672:15672"
      #- "15692:15692"
      #- "25672:25672"