version: '3.7'

services:
  
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=yourStrong(!)Password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
    mysql:
